### ISSUE TITLE
Terminate on retrun an error

### ISSUE THREAD

**Issue by mohammadrezaprw** [senecajs/seneca-mesh#68]
When i use http or  tcp type and  return (err,res) where err is not null, service terminate!
Is it a normal behavior?
If yes, how we can return an error with err-res pattern?
```javascript
 var Seneca = require('seneca');
 Seneca({log: 'test', timeout: '1000'})
        .use('seneca-transport')
        .use('mesh', {
            isbase: false,
            listen: [
                {pin: 'cat:test,cmd:run1', timeout: 1000, type: 'tcp'}
            ]
        })
        .add('cat:test,cmd:run1',function(msg,callback){
            callback(new Error('my error'));
        });
```
And here is act result that call from another service :
>  Seneca Fatal Error
==================
Message: seneca: Action cat:test,cmd:run1 failed: my error.
Code: act_execute
Details: { message: 'my error',
pattern: 'cat:test,cmd:run1',
instance: 'Seneca/fglbckoc6k4a/1479906487908/2721/3.2.2/-',
'orig$': {},
'message$': 'my error',
plugin: {} }
Stack:
at internals.Utils.handle_response (./node_modules/seneca-transport/lib/transport-utils.js:70:11)
at Duplex.messager._write (./node_modules/seneca-transport/lib/tcp.js:186:19)
...
...
SENECA TERMINATED at 2016-11-23T13:08:30.022Z. See above for error report.

**Comment by mohammadrezaprw** [comment]
@AdrianRossouw @mcollina @rjrodger @geek @darsee No answer?

**Comment by mcollina** [comment]
I am personally not maintaining seneca. Sorry.

**Comment by mohammadrezaprw** [comment]
@AdrianRossouw  @rjrodger @geek @darsee No answer?

**Comment by darsee** [comment]
@mohammadrezaprw I'm also not involved in the maintenance of this repository.

**Comment by mcollina** [comment]
Same here.

**Comment by rjrodger** [comment]
@mohammadrezaprw got it! this is now fixed- thanks for the bug report - this was a nasty one.
New release out shortly.

**Comment by Pulankit-so** [comment]
Hello, the issue still seems to exists.it worked fine with seneca-mesh 0.9.0. updating to seneca-mesh 0.10.0 has caused the same issue for me.  Also setting seneca,fixedargs.fatal = false is not helping
